FROM apache/nifi

# Install python3
USER root
# RUN cd /
# RUN apt-get -y update
# RUN apt-get -y install build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libsqlite3-dev libreadline-dev libffi-dev curl libbz2-dev
# RUN curl -o /Python-3.8.2.tar.xz https://www.python.org/ftp/python/3.8.2/Python-3.8.2.tar.xz
# RUN tar -xf /Python-3.8.2.tar.xz -C /
# RUN /Python-3.8.2/configure --enable-optimizations
# RUN /Python-3.8.2/install-sh


# Create log folder and copy script
RUN mkdir -p /var/log/jsonFormatter
RUN chown nifi:nifi /var/log/jsonFormatter
COPY --chown=nifi:nifi jsonFormatter.py /home/nifi/
