FROM apache/nifi

USER root

RUN apt-get update

RUN add-apt-repository -y ppa:deadsnakes/ppa

RUN apt install python3.8

RUN mkdir -p '/var/log/jsonFormatter'

RUN chown nifi:nifi '/var/log/jsonFormatter'

COPY --chown=nifi:nifi jsonFormatter.py /home/nifi/ 