FROM apache/nifi

# Install python3
USER root
RUN apt-get update -y
RUN apt-get install -y python3

# Create log folder and copy script
RUN mkdir -p /var/log/prometheus-ngsild-formatter
RUN chown nifi:nifi /var/log/prometheus-ngsild-formatter
RUN mkdir -p /var/log/avro-schema-metric-id
RUN chown nifi:nifi /var/log/avro-schema-metric-id
COPY --chown=nifi:nifi jsonFormatter.py /home/nifi/
